remote_theme: pages-themes/minimal
plugins:
- jekyll-remote-theme
title: Salih Cem Eroğlu
description: Sayfama hoş geldiniz! Yeni güncellemeler için sayfamı sık kullanılanlar kısmına eklemeyi unutmayın!
